version: '3'
services:
  mythesis:
    build: .
    image: 'tsungbao/mythesis'
    volumes:
      - './docker_volume:/thesis/docker_volume'
    command: ' tail -F anything'
              # To avoid the container from exiting right after all the 
              # commands are done